apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 2001
        runAsUser: 2001
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}{{ .Values.image.repositoryPath }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "100m"


